version: '3.7'
services:
   client:
      build:
         context: ./frontend
         dockerfile: Dockerfile-prod
      tty: true
      ports:
         - "3000:80"
      volumes:
         - ./frontend:/app
         - /app/node_modules
      networks:
            - frontend

   mongodb:
      image: mongo
      container_name: mongo
      restart: unless-stopped
      command: mongod --auth
      environment:
         MONGO_INITDB_ROOT_USERNAME: "admin"
         MONGO_INITDB_ROOT_PASSWORD: "test1234"
         MONGO_INITDB_DATABASE: mcdDB
         MONGODB_DATA_DIR: /data/db
      volumes:
         - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
         - mongodbdata:/data/db
      networks:
         - backend

   api:
      build:
         context: ./backend/
         dockerfile: Dockerfile
      ports:
         - "5000:5000"
      environment:
         MONGODB_HOST: mongodb
         MONGODB_USERNAME: "admin"
         MONGODB_PASSWORD: "test1234"
         PORT: 5000
         FLASK_DEBUG: 1
      volumes:
         - ./backend/:/app/
      depends_on: 
         - mongodb
      networks:
         - frontend
         - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local